spring:
  application:
    name: payment-worker

  datasource:
    url: jdbc:postgresql:///farmatodo?cloudSqlInstance=prueba-farmatodo-478406:us-central1:farmatodo-postgres&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 30000
      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    gcp:
      pubsub:
        enabled: ${PUBSUB_ENABLED:false}
        project-id: ${GCP_PROJECT_ID:prueba-farmatodo-478406}
      sql:
        enabled: false  # para que no choque con nuestro datasource manual

server:
  port: ${PORT:8080}

app:
  payment-rejection-probability: ${PAYMENT_REJECTION_PROBABILITY:0.2}
  max-payment-attempts: ${MAX_PAYMENT_ATTEMPTS:3}

ORDER_SERVICE_URL: ${ORDER_SERVICE_URL:http://localhost:8085}
AUTH_SERVICE_URL: ${AUTH_SERVICE_URL:http://localhost:8081}
API_KEY: ${API_KEY:test-api-key-12345}

logging:
  level:
    com.farmatodo: DEBUG
    org.springframework.web: INFO
